/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.ifies.android;

public final class R {
    public static final class array {
        public static final int alert_list_keys=0x7f040000;
    }
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundColor=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int isGoneWithoutAd=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int keywords=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int refreshInterval=0x7f010003;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f010001;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int question=0x7f020001;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f06000a;
        public static final int ScrollView01=0x7f060009;
        public static final int ad=0x7f060000;
        public static final int alert1=0x7f060002;
        public static final int alert2=0x7f060003;
        public static final int alert3=0x7f060004;
        public static final int alert4=0x7f060005;
        public static final int button_go=0x7f060014;
        public static final int enter_uri=0x7f060015;
        public static final int example_admod=0x7f06000c;
        public static final int example_alerts=0x7f06000e;
        public static final int example_gallery=0x7f06000d;
        public static final int example_location=0x7f060011;
        public static final int example_message=0x7f060001;
        public static final int example_rss_parser=0x7f06000f;
        public static final int example_webkit_view=0x7f060010;
        public static final int gallery=0x7f060006;
        public static final int layout_zoom=0x7f060008;
        public static final int mapview=0x7f060007;
        public static final int rss_all_items=0x7f060013;
        public static final int rss_item_title=0x7f060012;
        public static final int welcome=0x7f06000b;
        public static final int wv1=0x7f060016;
    }
    public static final class layout {
        public static final int admob_example=0x7f030000;
        public static final int alert_home=0x7f030001;
        public static final int gallery_example1=0x7f030002;
        public static final int location_example=0x7f030003;
        public static final int main=0x7f030004;
        public static final int rss_item=0x7f030005;
        public static final int rss_list=0x7f030006;
        public static final int simple_list_item_1=0x7f030007;
        public static final int webview_example=0x7f030008;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
    public static final class styleable {
        /** Attributes that can be used with a Gallery1.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #Gallery1_android_galleryItemBackground org.ifies.android:android_galleryItemBackground}</code><td></tr>
           </table>
           @see #Gallery1_android_galleryItemBackground
         */
        public static final int[] Gallery1 = {
            0x0101004c
        };
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#android_galleryItemBackground}
          attribute's value can be found in the {@link #Gallery1} array.
          @attr name android:android_galleryItemBackground
        */
        public static final int Gallery1_android_galleryItemBackground = 0;
        /** Attributes that can be used with a com_admob_android_ads_AdView.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_backgroundColor org.ifies.android:backgroundColor}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_isGoneWithoutAd org.ifies.android:isGoneWithoutAd}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_keywords org.ifies.android:keywords}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_refreshInterval org.ifies.android:refreshInterval}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_textColor org.ifies.android:textColor}</code><td></tr>
           </table>
           @see #com_admob_android_ads_AdView_backgroundColor
           @see #com_admob_android_ads_AdView_isGoneWithoutAd
           @see #com_admob_android_ads_AdView_keywords
           @see #com_admob_android_ads_AdView_refreshInterval
           @see #com_admob_android_ads_AdView_textColor
         */
        public static final int[] com_admob_android_ads_AdView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004
        };
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#backgroundColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:backgroundColor
        */
        public static final int com_admob_android_ads_AdView_backgroundColor = 0;
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#isGoneWithoutAd}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:isGoneWithoutAd
        */
        public static final int com_admob_android_ads_AdView_isGoneWithoutAd = 4;
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#keywords}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:keywords
        */
        public static final int com_admob_android_ads_AdView_keywords = 2;
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#refreshInterval}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:refreshInterval
        */
        public static final int com_admob_android_ads_AdView_refreshInterval = 3;
        /**
          <p>This symbol is the offset where the {@link org.ifies.android.R.attr#textColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textColor
        */
        public static final int com_admob_android_ads_AdView_textColor = 1;
    };
}
